# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'LocusLabsSamplesSwift' do
  use_frameworks!

  # Pods for LocusLabsSamplesSwift
  pod 'LocusLabs-iOS-SDK', '3.0.0-RC1'
end
