# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'LocusLabsSamplesSwift' do
  use_frameworks!

  # Pods for LocusLabsSamplesSwift
  pod 'LocusLabs-iOS-SDK', '3.2.0'

  # Only needed if integrating GRAB
  pod 'CardIO'
end
