# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LocusLabsSamplesSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LocusLabsSamplesSwift
  pod 'LocusLabs-iOS-SDK', '~> 3.0.0-beta3'
end
