# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'LocusLabsSamples' do
  
  use_frameworks!

  # Pods for LocusLabsSamples
  pod 'LocusLabs-iOS-SDK', '~> 3.0.0-beta7'
end
